### ISSUE TITLE
Tabs content empty with chrome

### ISSUE THREAD

**Issue by nikto1** [zutigrm/turbotabs#2] opened 2015-08-05 00:04 UTC
I was testing your plugin on the demo size with chrome (newest version). Just resize the browser, then change a tab and you see the new tab empty. If you want, i can send you a screenshot.

**Comment by zutigrm** [comment] 2015-08-05 08:42
It's hardly a browser issue,( especially a newest version, there can be problems with some old versions ), if you are talking about accordion mode, opening a blank tab, then if I understood propertly, that's an rendering error that occurred  in transition from tabs, to accordion, where transition animation hasn't disabled, (when tabs shifts to accordion, transition animation will be turned off, so that kind of stuff wouldn't happen), but on the first demo page, the one with controls previewer, it can happen sometime, because I had to "hack" the preview tab to include live preview of  all the options that are applied instantly as you change them. Check any other demo in same browser, and there should be no such problems.

**Comment by nikto1** [comment] 2015-08-05 19:32
a) Yep, but the rendering error only happens with chrome (maybe also in opera, who knows), on other browsers it's fine.

b) This happens also  if you click on the "just another tab" demo, same issue.

c) There's a fixed height in the main wrapper (like => http://goo.gl/q7RbJ3). If you resize the browser, the fixed height remains, and the overflow of the <p> is hidden. Maybe it would be better to set the height to "auto", 'cause a fixed height isn't really responsive.

d) There are also other minor bugs with this plugin, e.g. [HERE](http://goo.gl/q7RbJ3) transition between tabs is not running smoothly.

My way of thinking is:  "keep things simple but functional".
If people want something more, they could add it by themselves.

**Comment by zutigrm** [comment] 2015-08-05 20:05
Wrong fixed height in main demo, is probably due to, like I mentioned, 'hacked' approach of producing that live previewer, and every other issue that shows on that page, is most probably caused by that. If same error shows on other examples, than it is a plugin bug. Height isn't fixed by default, it is produced by means of javascript that measures  the highest tab height and apply it to a parent container, every time window is resized, which actually makes it "responsive". It cannot be set to auto because it is holding absolutely positioned chilldren elements.

I will fix rendering errors when I find some time to release next version that will include few fixes and some additions.

**Comment by zutigrm** [comment] 2015-09-28 18:57
Issues fixed in new version 1.2 release. Transition between tabs is now running smoothly and new tabs are not empty when resized.

**Closed as completed by zutigrm** 2015-09-28 18:57 UTC
